### ISSUE TITLE
Unable to read scan response data of devices which are advertising

### ISSUE THREAD

**Issue by katjie** [ThomasGerstenberg/blatann#118]
This is more of a feature request, but I have noticed that while I can read the advertising data from scan reports, I am unable to read the scan response of the same devices. At the moment, I need to be able to read the scan response as well as it contains information about what type of device I am connecting to.

Ideally, as I am able to do 

```
for report in self.ble.scanner.start_scan().scan_reports:
    if report.peer_address == addr:
        return report.advertise_data
```

I would also like to be able to do:

```
for report in self.ble.scanner.start_scan().scan_reports:
    if report.peer_address == addr:
        return report.scan_response
```

Or similar.

Maybe this feature already exists and I have missed it in the documentation?

**Comment by ThomasGerstenberg** [comment]
There's a slight limitation of the Nordic API where advertising data and scan response data is sent as separate events. The `advertise_data` is actually a combination of both, however due to the Nordic API the `scan_reports` iterable will have 2 entries: One with just the initial advertising data and a second with both advertising AND scan response data combined.

I haven't figured out the best way to handle this. A naive approach would be to wait for the scan response then emit only one entry, however not all devices have a scan response packet so things get a bit tricky from there.

If you don't need the scan response packet in real-time, one workaround would be to wait for the scan to finish, then iterate the reports which will have both advertising and scan response data. A semi real-time workaround would be to scan for a short period (e.g. 1 second) and check after each 1 second scan. An example of this can be seen [here](https://github.com/ThomasGerstenberg/blatann/blob/master/blatann/examples/scanner.py#L24-L29)

**Comment by katjie** [comment]
Okay, great. It helped to know that the advertise_data was a combination of both, at least after the scan is complete. Turns out I already had the implementation elsewhere, I just needed to use it correctly.

Thanks for the update, I believe we can close this issue unless you would like to leave it as a "improvement".
