### ISSUE TITLE
Advertiser:is_advertising might return False when auto_restart is set and adv timeouts

### ISSUE THREAD

**Issue by jupe** [ThomasGerstenberg/blatann#42]
If `auto_restart` is set and code are middle of adv timeout there is chance that property `is_advertising` returns False even it probably should return True in this case.

This leads situation where application top of library cannot rely on `is_advertising` property when toggling advertisement on and off.

**Comment by ThomasGerstenberg** [comment]
Thanks @jupe, I originally reasoned that since the state of the hardware in between restarts is a non-advertising state that it should be reflected as such. However I definitely understand and agree with the reasoning that the software advertising state should be reflected as `True` if auto_restart is enabled, since the intention is to resume advertising immediately with minimal interruption.

Will fix for the next release 👍
